#!/usr/bin/env bash

# Install Brew Packages
brew install tree

# Install MacOS Applications
brew install --cask google-chrome
brew install --cask spotify
brew install --cask discord
brew install --cask thinkorswim
brew install --cask omnidisksweeper
#brew install --cask zoomus
#brew install --cask virtualbox
#brew install --cask pycharm-ce
